%% An exemplary MEX-compilation file for compilation on MacOS

M=0;

mex -setup c++

% See here for manual compiler setup:
% https://github.com/Homebrew/discussions/discussions/3526 
% https://github.com/danfortunato/matlab-gcc
mex('-v', '-R2018a' ,...
    [ ...
        'CXXFLAGS="$CXXFLAGS' ...
            ' -Wall'...
            ' -Wextra' ... 
            ' -Wno-unused-parameter' ...
            ' -Wno-ignored-qualifiers' ...
            ' -Wno-unused-variable' ...
            ' -Wno-unused-command-line-argument'...
            ' -gline-tables-only' ...
		    ' -gcolumn-info' ...
            ' -std=c++20' ...
            ' -fno-math-errno' ...
            ' -pthread' ...
            ' -flto' ...     
            ' -ffast-math' ...
            ' -Ofast' ...
            ' -framework Accelerate' ...
            ' -framework OpenCL' ...
            ' -march=native -mtune=native -fveclib=SVML' ...   
            ' -fenable-matrix' ...
            ' -I./../../submodules/BAEMM' ...  
    '"'] ...
    , ...
    [ ...
        'LDFLAGS="$LDFLAGS' ...
            ' -lm' ...
            ' -ldl' ...
            ' -framework Accelerate' ...
            ' -framework OpenCL' ...
    '"'] ...
    , ...
    'FarField.cpp'...
    );
